
spring:

  # H2 Connection

  datasource:

    url: jdbc:h2:mem:testdb

    username: sa

    password: ""

  # H2 Client

  h2:

    console:

      enabled: true

      path: /h2-console

  jpa:

    # Show SQL

    show-sql: true

    properties:

      hibernate:

        format_sql: true

    # Hibernate Settings

    hibernate:

      ddl-auto: update

    database-platform: org.hibernate.dialect.H2Dialect
